services:
#  expeditions:
#    build:
#      context: .
#      dockerfile: apps/expeditions/Dockerfile
#      target: development
#    command: npm run start:dev
#    ports:
#      - "3000:3000"
#    volumes:
#      - .:/usr/src/app
#    env_file:
#      - apps/expeditions/.env
#    environment:
#      - NODE_ENV=development
  auth:
    build:
      context: .
      dockerfile: apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth
    env_file:
      - apps/auth/.env
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
  # postgres:
  #     image: postgres:latest
  #     environment:
  #       POSTGRES_USER: postgres
  #       POSTGRES_PASSWORD: password
  #       POSTGRES_DB: expeditions_db
  #     ports:
  #       - "5432:5432"
